[tool.poetry.dependencies]
python = ">=3.6, <3.10"
streamlit = "1.38.0"
torch = "2.4.0"
TTS = "0.6.0"
speechrecognition = "3.10.0"
pydub = "0.25.1"
PyPDF2 = "1.26.0"
pytesseract = "0.3.10"
pillow = "9.5.0"
